### ISSUE TITLE
Seems broken with LO 5.0.4 and LO 4.2.8

### ISSUE THREAD

**Issue by mathieumd** [XRoemer/Organon#72]
On two machines, one Debian Testing (Stretch) with LO 5.0.4, and another with Kubuntu 14.04 with LO 4.2.8, the installation of [organon.oxt](https://github.com/XRoemer/Organon/blob/master/organon.oxt) (v0.9.9.8.4b) seems to work well, but Organon is defunct and not usable:
- the menu "Organon" only contains a single entry "open/close";
- the "open/close" entry open a popup with nothing but the Organon logo;
- this popup is titled "Organon: dockable window", but it cannot be docked as a LO toolbar;
- the "Organon" toolbar (on the right, by default) open a panel with nothing but "No Project loaded";
- I cannot find where to create a new project;
- the help has not been opened (the [Organon Manual.pdf](https://github.com/XRoemer/Organon/blob/master/Organon%20Manual.pdf) says it should have been automatically opened).

I found #43 says that LO 5.0 is not compatible yet. But what about LO 4.2 on Ubuntu?
Is there a compatibility matrix somewhere?

Seems a nice project, though, by the way! :smiley:

**Comment by XRoemer** [comment]
Hi Mathieu,

thanks for your report.
I know there might be docking issues on some Linux distributions.
I'll have a closer look tomorrow on that and on the other issues you 
mentioned.

Greetings,
Xaver



Am 13.12.2015 um 17:29 schrieb Mathieu MD:

**Comment by XRoemer** [comment]
Hi Mathieu,
you wrote:

- the menu "Organon" only contains a single entry "open/close";
- the "open/close" entry open a popup with nothing but the Organon logo;
- the "Organon" toolbar (on the right, by default) open a panel with nothing but "No Project loaded";

That's the intendet behaviour. But the popup window should contain three buttons as well:
- Open Project
- New Project
- Open Manual

If they are missing it's a bug. Have a look if there is the error_log.txt file.
On my machine the path looks like:
/opt/libreoffice4.4/share/uno_packages/cache/uno_packages/luzlxd4g.tmp_/organon.oxt
For every extension exists another cryptic named folder like luzlxd4g.tmp_
(There might be a file error_log.txt already in this folder, as Organon logs all errors automatically.)

When a project is created or loaded the sidebar entry changes.

you wrote:
- this popup is titled "Organon: dockable window", but it cannot be docked as a LO toolbar;

It depends on your windows manager. For me it works with xfce, gnome and kde. But it's tricky sometimes. See: #12 

you wrote:
- the help has not been opened (the Organon Manual.pdf says it should have been automatically opened).

Maybe that's a misunderstanding. There is no automatic help file. But the manual can be opened on start up.

I hope, that helps.
Xaver

**Comment by XRoemer** [comment]
As I didn't receive any answer or other reports I close this one. If there are further problems, reopen it.

**Comment by mathieumd** [comment]
Hi Xaver,

Thanks for your reply.

# Cannot create project

I do confirm that there is nothing in the Organon popup, even when its window is fullsize: no "Open Project", nothing; only the logo in the bakground.

Please find attached the [error_log.txt](https://github.com/XRoemer/Organon/files/67478/error_log.txt).

Here is the bit which is append to the log when I click the menu _Organon > open/close_, which opens the empty popup:
```
### ERROR ###1
Traceback (most recent call last):
  File "/home/mathieu/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu133432vlkro.tmp_/organon.oxt/py/menu_start.py", line 296, in lade_Modul_Language
    lang = vars()[lang_en]
KeyError: <module 'lang_en' from '/home/mathieu/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu133432vlkro.tmp_/organon.oxt/languages/lang_en.py'>

### ERROR ###1
Traceback (most recent call last):
  File "/home/mathieu/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu133432vlkro.tmp_/organon.oxt/py/factory.py", line 717, in start_main
    Menu_Start.erzeuge_Startmenu()
  File "/home/mathieu/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu133432vlkro.tmp_/organon.oxt/py/menu_start.py", line 191, in erzeuge_Startmenu
    model.Label = self.LANG.NEW_PROJECT
AttributeError: 'NoneType' object has no attribute 'NEW_PROJECT'
```

Oh, according to that, it seems related to my locale, which is `fr_FR.UTF-8`.

If I launch LO with English locale, the popup at last contains the three buttons and I can create a project!
```bash
LC_ALL=en_US.UTF-8 libreoffice
```

OK, it seems to work.

# Create project

By the way, when I click "Create Project", the log shows these errors, but nevertheless, it seems to works:
```
0.66      sidebar     Sidebar                 erzeuge_sb_layout               ( caller: ElementFactory.createUIElement )       
Traceback (most recent call last):
  File "/home/mathieu/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu133432vlkro.tmp_/organon.oxt/py/sidebar.py", line 127, in erzeuge_sb_layout
    self.dict_container,self.dict_felder = container_erzeugen(panelWin)
  File "/home/mathieu/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu133432vlkro.tmp_/organon.oxt/py/sidebar.py", line 69, in container_erzeugen
    for panel_nr in self.mb.tags['abfolge']:
TypeError: 'NoneType' object is not subscriptable
### ERROR ###1
Traceback (most recent call last):
  File "/home/mathieu/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu133432vlkro.tmp_/organon.oxt/py/sidebar.py", line 127, in erzeuge_sb_layout
    self.dict_container,self.dict_felder = container_erzeugen(panelWin)
  File "/home/mathieu/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu133432vlkro.tmp_/organon.oxt/py/sidebar.py", line 69, in container_erzeugen
    for panel_nr in self.mb.tags['abfolge']:
TypeError: 'NoneType' object is not subscriptable
```

But I can create a project, edit its files, and (apparently) save it without further error messages.

# Open project

But when I try to open a project -- from one of the three buttons in the first popup -- it fails with this messages in logs:
```
factory init
2.66      projects    Projekt                 lade_Projekt                    ( caller: Menu_Listener.actionPerformed )        
### ERROR ###1
Traceback (most recent call last):
  File "/home/mathieu/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu133432vlkro.tmp_/organon.oxt/py/projects.py", line 659, in lade_Projekt
    filepath,ok = self.mb.class_Funktionen.filepicker2(filter=filter,sys=True)
  File "/home/mathieu/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu133432vlkro.tmp_/organon.oxt/py/funktionen.py", line 667, in filepicker2
    file_len = len(Filepicker.getSelectedFiles())
AttributeError: getSelectedFiles

Traceback (most recent call last):
  File "/home/mathieu/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu133432vlkro.tmp_/organon.oxt/py/projects.py", line 659, in lade_Projekt
    filepath,ok = self.mb.class_Funktionen.filepicker2(filter=filter,sys=True)
  File "/home/mathieu/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu133432vlkro.tmp_/organon.oxt/py/funktionen.py", line 667, in filepicker2
    file_len = len(Filepicker.getSelectedFiles())
AttributeError: getSelectedFiles

2.66      projects    Projekt                 lade_Projekt                    ( caller: Menu_Listener.actionPerformed )        
```

When I try to open the same project from the _File > Open project_ menu into the popup, it fails too, and the logs are:
```
0.74      projects    Projekt                 lade_Projekt                    ( caller: Auswahl_Menu_Eintrag_Listener.mousePres
s
Traceback (most recent call last):
  File "/home/mathieu/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu133432vlkro.tmp_/organon.oxt/py/projects.py"
, line 659, in lade_Projekt
    filepath,ok = self.mb.class_Funktionen.filepicker2(filter=filter,sys=True)
  File "/home/mathieu/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu133432vlkro.tmp_/organon.oxt/py/funktionen.p
y", line 667, in filepicker2
    file_len = len(Filepicker.getSelectedFiles())
AttributeError: getSelectedFiles
### ERROR ###1
Traceback (most recent call last):
  File "/home/mathieu/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu133432vlkro.tmp_/organon.oxt/py/projects.py", line 659, in lade_Projekt
    filepath,ok = self.mb.class_Funktionen.filepicker2(filter=filter,sys=True)
  File "/home/mathieu/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu133432vlkro.tmp_/organon.oxt/py/funktionen.py", line 667, in filepicker2
    file_len = len(Filepicker.getSelectedFiles())
AttributeError: getSelectedFiles


0.74      projects    Projekt                 lade_Projekt                    ( caller: Auswahl_Menu_Eintrag_Listener.mousePress
0.74      menu_bar    Auswahl_Menu_Eintrag_L  mousePressed                    ( caller: .EventObject )                         
### ERROR ###1
Traceback (most recent call last):
  File "/home/mathieu/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu133432vlkro.tmp_/organon.oxt/py/projects.py", line 659, in lade_Projekt
    filepath,ok = self.mb.class_Funktionen.filepicker2(filter=filter,sys=True)
  File "/home/mathieu/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu133432vlkro.tmp_/organon.oxt/py/funktionen.py", line 667, in filepicker2
    file_len = len(Filepicker.getSelectedFiles())
AttributeError: getSelectedFiles

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mathieu/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu133432vlkro.tmp_/organon.oxt/py/menu_bar.py"
, line 1739, in mousePressed
    self.mb.class_Projekt.lade_Projekt()
  File "/home/mathieu/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu133432vlkro.tmp_/organon.oxt/py/projects.py"
, line 735, in lade_Projekt
    if e.typeName == 'com.sun.star.task.ErTraceback (most recent call last):
  File "/home/mathieu/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu133432vlkro.tmp_/organon.oxt/py/projects.py"
, line 659, in lade_Projekt
    filepath,ok = self.mb.class_Funktionen.filepicker2(filter=filter,sys=True)
  File "/home/mathieu/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu133432vlkro.tmp_/organon.oxt/py/funktionen.p
y", line 667, in filepicker2
    file_len = len(Filepicker.getSelectedFiles())
AttributeError: getSelectedFiles

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mathieu/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu133432vlkro.tmp_/organon.oxt/py/menu_bar.py"
, line 1739, in mousePressed
    self.mb.class_Projekt.lade_Projekt()
  File "/home/mathieu/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu133432vlkro.tmp_/organon.oxt/py/projects.py"
, line 735, in lade_Projekt
    if e.typeName == 'com.sun.star.task.ErrorCodeIOException':
AttributeError: 'AttributeError' object has no attribute 'typeName'
rorCodeIOException':
AttributeError: 'AttributeError' object has no attribute 'typeName'
```

Which make Organon not usable yet, unfortunately :disappointed:

**Comment by XRoemer** [comment]
Hi Mathieu,

you're right. Any other language than english, german or italien won't show the entry menu. I've changed that and uploaded a new version here on github (v0.9.9.8.6b). Download the zipfile, unzip and use the organon.oxt.
On the OO extension site Organon is disabled at the moment and will appear within the next hours/days again.

You're second and third error comes from code from v0.9.8.8.4b or lower. So that should already be solved.

The new version still has issues, but should work. I hope to get ready and release an almost stable version within the next weeks.

**Comment by mathieumd** [comment]
I'm sorry Xaver, but even with the v0.9.9.8.6b, I still cannot open a project. I even tried to create a new project with this version, save it, close LO, then try to open it back, with no luck.

The log only shows:
```
### ERROR ###1
Traceback (most recent call last):
  File "/home/mathieu/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu23925dmmud2.tmp_/organon.oxt/py/projects.py", line 659, in lade_Projekt
    filepath,ok = self.mb.class_Funktionen.filepicker2(ofilter=ofilter,sys=True)
  File "/home/mathieu/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu23925dmmud2.tmp_/organon.oxt/py/funktionen.py", line 670, in filepicker2
    file_len = len(Filepicker.getSelectedFiles())
AttributeError: getSelectedFiles
```

Just to be sure, the Organon project file is the `<project_name>.organon` file, containing `Dies ist eine Organon Datei. Goennen Sie ihr ihre Existenz.`, located into the `<project_name>.organon` folder, right?

**Comment by mathieumd** [comment]
Oh, but I forgot to confirm that even `fr_FR.UTF-8` locale now works. Thanks. :-)

**Comment by XRoemer** [comment]
Ok, I found your bug. Is it on both LO 5 and LO 4.2?
I'm testing at the moment if it works on my platforms and on OO as well.

Cheers,
Xaver



Am 19.12.2015 um 22:56 schrieb Mathieu MD:

**Comment by XRoemer** [comment]
I've uploaded a new version (v0.9.9.8.6b - v.2 
<https://github.com/XRoemer/Organon/commit/b68f7d827be2f0717362a65263a4a77ea7294b43>) 
to github.
It works for me on win7, Fedora 22 and Ubuntu 15.05
It might produce an error, if you try to load a project but cancel the 
file selection. But that error isn't important.

Xaver





Am 19.12.2015 um 22:56 schrieb Mathieu MD:

**Comment by mathieumd** [comment]
Perfect! :+1:
It works for me on Debian 9.0 Stretch with LO 5.0.4.
I will have my friend test it on Kubuntu 14.04 with LO 4.2.8.
Thank you Xaver :smiley:

**Comment by XRoemer** [comment]
Hi Mathieu,

Have a look at the other issues. There are some serious ones, like #68, 
#83, #84, #85.
I'll do another release tonight or tomorrow, to get them fixed.
If you find any other, post them!

Greetings,
Xaver





Am 20.12.2015 um 10:13 schrieb Mathieu MD:
